"""Add closed_at_price to Trade

Revision ID: 30419a9731c3
Revises: 56f4a59f16d3
Create Date: 2026-04-04 09:58:28.088749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30419a9731c3'
down_revision: Union[str, None] = '56f4a59f16d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.add_column(sa.Column('closed_at_price', sa.Numeric(precision=18, scale=8), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_column('closed_at_price')

    # ### end Alembic commands ###
